### ISSUE TITLE
Mixes of portuguese and english in PR's

### ISSUE THREAD

**Issue by paulohenriquepm** [GeekHunter-Brasil/hello-world#15]
We have a culture to write the PR's description in Portuguese, but the comments, reviews, and discussions in English. Shouldn't we choose one language and use it for all types of communications inside Github?

An observation to be made is that the data_science teams sometimes need to review our PR's and they always write their comments in Portuguese.

What do you think about it?

**Comment by pedro-lb** [comment]
I completely agree.

For me personally, it's easier to keep in English since our code is 100% English - that means less context switching and more efficiency. This may also be aligned with some people since it's common to have english as a skill to develop.

However, that may be an unnecessary barrier to overcome - so I'm open to suggestions =)

**Comment by vghellere** [comment]
I prefer English as well

**Comment by Thrashattack** [comment]
I agree that we should padronize the language just as we do with everything related to our job. 
And since we are setting a standart language i understand that it should be the main language of the codebase that is English. 
Also, since we are focusing to become a reference in Software Development is unavoidable that in sometime we will need to lead our meetings also in english, due to the diversity of people from another countrys.

**Comment by joaophellip** [comment]
+1 for English!

I'm of the view that document/communicate in English helps us to better consume/colaborate with tech community as a whole. Another reason to use English as official language for PRs/CRs is that it avoids unnecessary translations of db fields and/or terms (ex: empresa estagnada/limbo) which can lead to confusion.
